# Generated by Django 5.1 on 2024-09-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=50)),
                ('version_range', models.CharField(blank=True, max_length=255, null=True)),
                ('support_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('remediation_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=20)),
                ('cwe_id', models.CharField(max_length=20)),
                ('cwe_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('base_score', models.FloatField()),
                ('base_severity', models.CharField(max_length=50)),
                ('vector_string', models.CharField(max_length=255)),
                ('cvss_version', models.CharField(max_length=10)),
                ('products', models.ManyToManyField(related_name='vulnerability_products', to='product_CVE.product')),
            ],
        ),
    ]
